# Generated by Django 5.0.4 on 2024-06-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vg_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
