# Generated by Django 5.0.4 on 2024-06-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vg_app', '0002_delete_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_proyecto', models.CharField(blank=True, max_length=100)),
                ('descripcion_proyecto', models.TextField(blank=True)),
                ('categoria_proyecto', models.CharField(blank=True, max_length=50)),
                ('archivo_proyecto', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
