# Generated by Django 5.0.4 on 2024-06-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vg_app', '0004_producto_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfildev',
            name='imagen_perfil',
            field=models.ImageField(blank=True, default='icono.jpg', upload_to='imagenes/'),
        ),
    ]
