# Generated by Django 5.0.4 on 2024-06-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vg_app', '0009_alter_perfildev_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfildev',
            name='nombre_perfil',
            field=models.CharField(blank=True, default='Sin nombre', max_length=50),
        ),
    ]
